# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Chris/Documents/GitHub/CECS_460/ProjectOne_460_blaze/ProjectOne_460_blaze.srcs/sources_1/ip/scratch_ram/scratch_ram.xci
# IP: The module: 'scratch_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Chris/Documents/GitHub/CECS_460/ProjectOne_460_blaze/ProjectOne_460_blaze.srcs/sources_1/ip/scratch_ram/scratch_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'scratch_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Chris/Documents/GitHub/CECS_460/ProjectOne_460_blaze/ProjectOne_460_blaze.srcs/sources_1/ip/scratch_ram/scratch_ram.xci
# IP: The module: 'scratch_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Chris/Documents/GitHub/CECS_460/ProjectOne_460_blaze/ProjectOne_460_blaze.srcs/sources_1/ip/scratch_ram/scratch_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'scratch_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
