# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Chris/Documents/GitHub/CECS_460/project_2/project_2.srcs/sources_1/ip/tb_rom_1/tb_rom.xci
# IP: The module: 'tb_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Chris/Documents/GitHub/CECS_460/project_2/project_2.srcs/sources_1/ip/tb_rom_1/tb_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tb_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Chris/Documents/GitHub/CECS_460/project_2/project_2.srcs/sources_1/ip/tb_rom_1/tb_rom.xci
# IP: The module: 'tb_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Chris/Documents/GitHub/CECS_460/project_2/project_2.srcs/sources_1/ip/tb_rom_1/tb_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tb_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
