# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Chris/Desktop/Github/cecs460/project_1/project_1.srcs/sources_1/new/Nexys4DDR_Master.xdc

# IP: ip/scratch_ram/scratch_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==scratch_ram || ORIG_REF_NAME==scratch_ram} -quiet] -quiet

# IP: ip/stack_ram/stack_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stack_ram || ORIG_REF_NAME==stack_ram} -quiet] -quiet
